### ISSUE TITLE
High CPU usage on Yosemite

### ISSUE THREAD

**Issue by ragingdave** [kbhomes/radiant-player-mac#246]
The Player seems to always be using the cpu pretty heavily.

Saw this in the console:
kernel[0]: process Radiant Player[3666] thread 123299 caught burning CPU! It used more than 50% CPU (Actual recent usage: 95%) over 180 seconds. thread lifetime cpu usage 90.108710 seconds, (81.791402 user, 8.317308 system) ledger info: balance: 90001499151 credit: 90003799116 debit: 2299965 limit: 90000000000 (50%) period: 180000000000 time since last refill (ns): 94357875096 

and This Diagnostic Report:
Command:         Radiant Player
Path:            /Applications/Radiant Player.app/Contents/MacOS/Radiant Player
Powerstats for:  Radiant Player [3666] thread 0x1e1a3
    44 main + 203 (Radiant Player) [0x107a6d505]
                                                                                1  __22-[PopupView drawRect:]_block_invoke + 52 (Radiant Player) [0x107a7baff]
                                                      3  -[PlaybackSliderCell drawWithFrame:inView:] + 168 (Radiant Player) [0x107a71ec7]
                                                          1  -[PlaybackSliderCell drawKnob:] + 847 (Radiant Player) [0x107a71aad]
                                                          1  -[PlaybackSliderCell drawKnob:] + 1033 (Radiant Player) [0x107a71b67]
                                                          1  -[PlaybackSliderCell drawKnob:] + 1653 (Radiant Player) [0x107a71dd3]
                                                1  -[PopupView drawRect:] + 676 (Radiant Player) [0x107a7b3ce]
                                                1  -[PopupView drawRect:] + 1660 (Radiant Player) [0x107a7b7a6]
         0x107a65000 -        0x107aacff7  com.sajidanwar.Radiant-Player 1.3.1 <74E6BEEA-AC22-3B3E-9D3E-9D3C209F437F> /Applications/Radiant Player.app/Contents/MacOS/Radiant Player
Powerstats for:  Radiant Player [3666] (other threads)
         0x107a65000 -        0x107aacff7  com.sajidanwar.Radiant-Player 1.3.1 <74E6BEEA-AC22-3B3E-9D3E-9D3C209F437F> /Applications/Radiant Player.app/Contents/MacOS/Radiant Player

Won't be able to use this until the usage goes down from a solid 100% usage at all times

**Comment by keyki** [comment]
Will there be a new release any time soon?

**Comment by DaveMC08** [comment]
I will preface this by saying that I really appreciate the time and effort that has gone into this project as it has gotten passed around developer to developer.  Being a developer myself I totally understand how issues arise after you have something working damn near perfect and then it breaks from external forces. But.....
Realistically, I am done with this app. Not just for the recent bugs that have plagued it mostly due to Yosemite changes, but also because it seems that google has managed to slip under the radar a similar application.  Certainly not as feature rich as this with last.fm integration and styles, but good enough for my purposes of....being able to use the media keys.  Using google chrome and presumably the google launcher that comes with it, I found the google music icon in launchpad or mission control or whatever the windows 8 start screen equates to in mac land.  Upon opening that up, I found that the resulting mini player that pops-up responds to media keys natively. 

AGAIN, I want to make it perfectly clear that I am in no way dissing the current or past devs, just wanted to let others know about this google easter egg.

**Comment by kbhomes** [comment]
I recognize how long it's taken me to respond to these issues, and I'm very sorry! If anybody is still interested in helping me get a new release out as soon as possible, please hop on over to #280 where I've included a prerelease version. I want to get user data on whether the performance issue has been taken care of.
