### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by kbhomes** [kbhomes/radiant-player-mac#280]
I'm making this issue to consolidate all the other performance issue threads that I believe are related. Some people have said that the performance issues have gone away when disabling notifications, or the mini player, or by compiling the most recent version from source.

Soon, I'm going to be uploading a pre-release version in this thread that you can test, and if you previously had performance issues, let me know how this version performs. If it works well then I should be able to push out a full release very shortly thereafter.

This issue encompasses #227, #246, #262, #275.

**Comment by kbhomes** [comment]
[Here is the prerelease version][1], please let me know how this performs!

[1]: https://drive.google.com/open?id=0B2ibKlBbCxFBZTdUMHR3Q1dRWEE&authuser=0

**Comment by hutchy2570** [comment]
Thanks.  As soon as I turned Album Art back on in the notification settings, the hanging started to occur right away with this build.

**Comment by jlongrc** [comment]
With the pre-release, I have turned on:
- mini player
- notifications
- album art
- custom theme (Yosemite)
- Last.fm
- keyboard listening
And am having no issues. I haven't used it extensively yet, but CPU usage while playing music is hovering around 8% (2014 MacBook Air, i5). Very brief, expected spikes when changing songs and the like. So far, so good!

**Comment by ccampbell** [comment]
I just noticed my version was hanging, came here, and found this issue.  I installed the prerelease version, but unfortunately no luck.  It is consistently using over 90% CPU (same as the current stable release).  The problem seems to start when I visit the "My Library" page.  I am on Mavericks (10.9.5).

**Comment by danfairs** [comment]
This seems to have fixed both high CPU usage and frequent audio pauses I was getting on Yosemite. Nice!

**Comment by akszydelko** [comment]
#275 - For first few seconds it was working quite nice but not for long. The problem starts to occur again.

**Comment by dodgepong** [comment]
On the pre-release, I got the same freezing when I enabled Notifications, Album Art, and iTunes-style notifications (froze after a few song plays). The freezing seemed to disappear once I disabled Album Art.

**Comment by jlongrc** [comment]
After about an hour of use, it skipped to the next song in the middle of another one. It never played the next one because it began to hang. Back to using it again with no problems, but it wouldn't shock me if something like this pops up again. At least the problems aren't totally persistent like before.

**Comment by kbhomes** [comment]
@jlongrc: Did you have album art enabled in notifications? There was a bug where that was causing the app to hang if the network was slow at the moment it was trying to download the album art (because the downloading blocked). If that's the case, then the new pre-release will probably help.

@dodgepong: I just pushed a fix for that album art freezing bug, I'll post the new pre-release soon.

**Comment by kbhomes** [comment]
Here you can download [pre-release version 2][1], give it a try.

[1]: https://drive.google.com/open?id=0B2ibKlBbCxFBX3JYQ0g5ZHBBSUU&authuser=0

**Comment by kbhomes** [comment]
@ccampbell: What style are you using? Can you try the Light theme or disable themes entirely and see if the CPU usage is still high?

@akszydelko: Same questions, what theme are you using and does disabling it improve the situation? Also, which version of OS X are you using?

**Comment by dodgepong** [comment]
I'll test the prerelease 2, thanks!

Before I forget, I should also point out this issue with back/forward that I noticed with both prereleases. I'm on 10.10.

![screen shot 2015-02-19 at 2 34 14 pm](https://cloud.githubusercontent.com/assets/838450/6274312/bc57ebfe-b844-11e4-815a-e07c7a391d6d.png)

**Comment by akszydelko** [comment]
@kbhomes I am using Dark flat theme. Turning off custom theme is not helping even a bit ;/. 
I am using Mavericks 10.9.5.

**Comment by ccampbell** [comment]
@kbhomes I was using the cocoa theme.  I just tried disabling themes and it still is using ~90-95% CPU.  I tried turning off swipe gestures as @akszydelko recommended, but that didn't seem to help for me.  I will try the prerelease version 2 in a little bit.

**Comment by dodgepong** [comment]
So far so good with Album Art enabled on notifications!

**Comment by rameshdharan** [comment]
@kbhomes I'm using the Prerelease version 2, and FWIW I see the same bug with the back forward buttons as @dodgepong. However the good news is the CPU usage does seem to be much better. I have the minelayer and album art notifications enabled and used to see consistent ~50% CPU usage as soon as I opened the app. 

Now it hovers around 8-9%. Still seems a bit too high, since the Flash Player process is using an additional 6% (which is presumably the actual audio decoding) so I don't really get what the main process is doing when nothing is being rendered or interacted with, but anyway it's an improvement for me.

**Comment by lucascampelo** [comment]
@kbhomes I tested the pre-release v2 for issue #275 and seems have the same problem..

**Comment by tthayer** [comment]
pre-release 2 is working great on Yosemite 10.10.2. Thanks!

**Comment by svyatogor** [comment]
CPU problem is gone indeed. One bug I noticed is that when switching desktops with swipe gesture the mini player will appear for ~1s and then disappear again. The problem doesn't start immediately after the app starts, but only after you open mini player at least once.

**Comment by shokk** [comment]
Is the pre-release still recommended over the release version for the above issues? 
I'm seeing higher CPU with 1.3.1 but want to hold out if the full version is being bumped up soon.

**Comment by simardcasanova** [comment]
Hey, I also confirm that this prerelease solved the high CPU usage on Yosemite.

**Comment by kbhomes** [comment]
Closing this issue because it appears this seems to have been fixed with 1.3.2!
