### ISSUE TITLE
[OS X 10.8] Empty screen in latest player

### ISSUE THREAD

**Issue by ggrell** [kbhomes/radiant-player-mac#291]
At some point Radiant stopped loading Google Music. Seems to load the top header area, but nothing else. Works fine in Safari 6.2.3.

Mac OS X 10.8.5

![screen shot 2015-03-23 at 11 34 58 am](https://cloud.githubusercontent.com/assets/107712/6784198/a7ec343a-d154-11e4-8021-94d08cc893bf.png)

**Comment by pstonebu** [comment]
Same thing on my end.

**Comment by jwmann** [comment]
Came here to also report the same.

It happened seemingly after I updated my Flash Player, not sure if it's related. 

OS X 10.8.5

![screen shot 2015-03-23 at 23 39 36](https://cloud.githubusercontent.com/assets/436270/6795438/21078142-d1b6-11e4-91a4-17736aa5877f.png)

**Comment by mrwizard65** [comment]
Same here. Happened after flash update.

**Comment by 48kRAM** [comment]
I"m also seeing this issue for about a week or so it seems. Only the top bar is present and the app is non-functional.

**Comment by slayer925** [comment]
same here. I can't wait to have radiant player working :(

**Comment by matt-cassidy** [comment]
I'm having the same issue on 10.8.5
![screen shot 2015-03-31 at 10 06 11 am](https://cloud.githubusercontent.com/assets/947742/6919483/bf5cb81c-d78d-11e4-88e3-64c4270cb054.png)

**Comment by jwmann** [comment]
I thought the issue might have been Safari Sandboxing the Flash player or something so I tried to use [this technique](https://helpx.adobe.com/flash-player/kb/removing-sandbox-restrictions-your-safari.html) to bypass that but didn't get any results :(

**Comment by kbhomes** [comment]
It seems this problem is limited in scope to OS X 10.8? I don't have immediate access to that version of OS X but will try to investigate as soon as I can.

**Comment by jwmann** [comment]
@kbhomes Hopefully you can figure something out.

Radiant Player essentially uses Safari as a WebView wrapper to load `https://play.google.com/music/listen` (as far as I understand) so I was thinking it had something to do with Safari playing nicely with Flash since it seemed to have happened directly after updating Flash.

If you'd like me to try something, let me know.

**Comment by kbhomes** [comment]
Could any of you try the latest 1.3.3.2-beta release and let me know how it works?

**Comment by Ch00k** [comment]
@kbhomes I'm still getting blank screen on 10.8.5. Maybe there is some kind of cache I have to clear or something like that?

**Comment by slayer925** [comment]
@kbhomes Now it won't crash, but the blank screen after google login is still there.

**Comment by jwmann** [comment]
This definitely fixes #325

The issue of an empty screen still remains. However, the issue is *slightly* different.

This is what happens. Bolded list items are new occurrences.

1. Open Radiant Player ( v1.3.3.2-beta )
2. Radiant Player Windows Opens.
3. **'Loading Google Play Music' message appears in the middle**
4. **Loading message disappears**
5. **Toolbar at the top is no longer shown, Google+ Profile (which is a part of the toolbar) at the top right is also no longer there**

![screen shot 2015-06-04 at 11 25 06 am](https://cloud.githubusercontent.com/assets/436270/7987603/84beafe2-0aac-11e5-9761-238e567084d4.PNG)
