### ISSUE TITLE
Yosemite skin improvements (work in progress)

### ISSUE THREAD

**Issue by FezVrasta** [kbhomes/radiant-player-mac#303]
I'm working on the Yosemite theme to make it look more similar to a native app like iTunes.
Would be okay if I send a PR with my edits?

I need a way to change the position of the window controls because they should be some some pixel higher...

Thanks!

**Comment by FezVrasta** [comment]
Made some progress on it:

![schermata 2015-04-09 alle 12 57 56](https://cloud.githubusercontent.com/assets/5382443/7065458/2dc7d5bc-deb8-11e4-9637-3841374ab734.png)
![schermata 2015-04-09 alle 12 57 34](https://cloud.githubusercontent.com/assets/5382443/7065459/2dcbc488-deb8-11e4-852e-fbadbbc7539a.png)
![schermata 2015-04-09 alle 12 58 08](https://cloud.githubusercontent.com/assets/5382443/7065460/2dd54d6e-deb8-11e4-8355-4e45369ca24c.png)
![schermata 2015-04-09 alle 12 57 40](https://cloud.githubusercontent.com/assets/5382443/7065461/2dd79bf0-deb8-11e4-92fc-49ffd6c77f12.png)

**Comment by FezVrasta** [comment]
Styled the progress bar:

![image](https://cloud.githubusercontent.com/assets/5382443/7066302/91bb6bd4-dec1-11e4-8993-404fb08092c0.png)

**Comment by FezVrasta** [comment]
@kbhomes could you kindly reply?

By the way I've improved the look and feel adding a different style to the header when inactive.
![image](https://cloud.githubusercontent.com/assets/5382443/7369105/24af39ba-edaf-11e4-9f05-1a6d967bc2e4.png)

**Comment by joshS314159** [comment]
Well. I like it personally. I've been ready to rid of titlebars since 2010.

Vertically center the toolbar more. Do something with the search bar to make it smaller...

Try to merge the controls with the top toolbar. Get rid of the (dis)like etc buttons...I'd just keep play and next, and maybe a longhand to go back somehow. That could be pretty and save a LOAD of space.

Trash back and forward navigation buttons. Most of us can swipe or use a keyboard.

Personally, I like it though. Friggin hate toolbars. And I realize my suggestions are really only my opinion. I dream of clean interfaces.

**Comment by quozd** [comment]
@FezVrasta where can I find patch with your improvements? 

Looks amazing

**Comment by bondt** [comment]
@FezVrasta, does it still work with Google's new design...?

**Comment by quozd** [comment]
Well, no. But I hope it will be fixed soon :)

**Comment by FezVrasta** [comment]
I'm not at home these days, next week I'll send a pr

**Comment by bondt** [comment]
<3

**Comment by FezVrasta** [comment]
Sorry, completely broken with new ui :(
